name: Metrics
on:
  schedule:
    - cron: 0 * * * *
  push: {}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 1000
          retries: 10
          repositories_affiliations: owner, collaborator
          base: ""
          output_action: commit
          committer_message: "[metrics] update metrics"
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          config_timezone: America/Los_Angeles

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: no
          plugin_isocalendar_duration: full-year

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
          plugin_achievements: true
          plugin_achievements_ignored: automater, stargazer, forker, gister # developer, member, explorer, infographile

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_skipped: nodejs/node
          plugin_languages_ignored: kotlin, C#, Coffeescript, Starlark, Smarty, C++, C, Perl, Arc, Swift, Java, Objective-C

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/sponsors/README.md
          plugin_sponsors: no
          plugin_sponsors_past: yes
